package com.cardprototype.core.domain;

/**
 * Different names of station
 *
 * @see Station
 * @author Kevin Deyne
 */
public enum StationName {

	DELTA(),
	ADINKERKE, AFFLIGEM, AISEAU, ALKEN, ALVERINGEM, AMAY, AMEL, ANDENNE, ANDERLECHT, ANDERLUES, ANHÉE, ANS, ANTHISNES, ARLON, AS, ASSEBROEK, ATH, AUBANGE, AVENNES, AYE, BASTOGNE, BEAUVECHAIN, BEERNEM, BEERST, BERLARE, BERNISSART, BIERBEEK, BIÈVRE, BLANKENBERGE, BOUILLON, BOVEKERKE, BRUGES, CHARLEROI, CHÂTELET, COUVIN, DAMME,
	DEFTINGE, DEURNE, DIKSMUIDE, DINANT, DOISCHE, DRONGEN, DUDZELE, DWORP, EERNEGEM, EGHEZÉE, EKEREN, ESEN, ESNEUX, ETTERBEEK, FARCIENNES, FLEURUS, FLOREFFE, FOSSESLAVILLE, FOY, GEDINNE, GERPINNES, GESVES, GHENT, GLONS, GOTEM, HANDZAME, HANNUT, HASSELT, HOUTHULST, HOUYET, JABBEKE, JEMAPPES, JODOIGNE, KAASKERKE, KEIEM, KLERKEN, KNOKKE, KNOKKEHEIST, KOEKELARE, KOKSIJDE, KOOLKERKE, KORTEMARK, KORTRIJK,
	LAKEN, LAMPERNISSE, LAPSCHEURE, LASNE, LEKE, LEUVEN, LIBRAMONTCHEVIGNY, LISSEWEGE, LIÈGE, LO, LOUVEIGNÉ, LUCHTEREN, MACON, MARCINELLE, MECHELEN, MELSEN, MERKEM, METTET, MOERKERKE, MONS, NAMUR, NEUFCHÂTEAU, NIEUWKAPELLE, NINOVE, NIVELLES, NOBRESSART, NOORDSCHOTE, OEDELEM, OHAIN, OHEY, OORDEREN, OOSTDUINKERKE, OOSTKERKE, OPDORP, OSTEND, OUDEKAPELLE, PERVIJZE, PERWEZ, PHILIPPEVILLE, PIRONCHAMPS, POLLINKHOVE, RAMSKAPELLE, REDU, RENINGE, SAIVE, SAMBREVILLE, SIJSELE, SNELLEGEM, SOMBREFFE, STALHILLE, STUIVEKENSKERKE, SÉLANGE, TILDONK, TINTIGNY, TOURNAI, UITKERKE, VARSENARE, VERVIERS, VISSENAKEN, VLADSLO, VRESSESURSEMOIS, WALCOURT, WALHAIN, WATERLOO, WAVRE, WERCHTER, WERKEN, WESTKAPELLE, WOUMEN, WÉPION, YVOIR;

	private StationName(){}

}
